### ISSUE TITLE
help

### ISSUE THREAD

**Issue by thefuture0821** [wnzzer/wifi-auto-connect#1]
怎么编辑那个jar包,来省略掉每次都要输账密的步骤.
用记事本打开是文字乱码

**Comment by thefuture0821** [comment]
![Uploading 屏幕截图 2024-11-01 113454.png…]()

**Comment by wnzzer** [comment]
可以手动编译直接把东西写死就行，只有一个文件，应该很简单吧

**Comment by thefuture0821** [comment]
0基础,怎么手动编译

**Comment by wnzzer** [comment]
外部那个配置文件配置了的话，后面也不用输入

**Comment by thefuture0821** [comment]
我配置了,但点这个.jar还是要输入

**Comment by thefuture0821** [comment]
![Uploading 微信截图_20241101114016.png…]()

**Comment by wnzzer** [comment]
jar同级目录创建一个 authentication.conf，内容入下，检测到就不会输入了
#校园网帐号
username=
#校园网密码
password=
#校园网运营商 移动为=yd,联通为lt,电信为dx.
operator=yd

**Comment by thefuture0821** [comment]
ok

**Comment by thefuture0821** [comment]
![Uploading 屏幕截图 2024-11-01 114256.png…]()

**Comment by thefuture0821** [comment]
不行

**Comment by thefuture0821** [comment]
我这个.jar是靠一个bat文件打开的,正常双击打不开,是这个影响了吗

**Comment by thefuture0821** [comment]
![image](https://github.com/user-attachments/assets/8e63514c-7652-49e8-986e-13dd9da5872b)

**Comment by thefuture0821** [comment]
![Uploading image.png…]()
我之前的截图你是不是都看不到

**Comment by wnzzer** [comment]
看不到图片，不过我试了， 确实有点问题，我改一下

**Comment by wnzzer** [comment]
已上传新的jar
